dependencies:
- name: inventory-management-bff-jpb
  version: 1.0.0-6
  repository: http://artifactory.mooc-two-ocp-cluster-0143c5dd31acd8e030a1d6e0ab1380e3-0000.eu-gb.containers.appdomain.cloud/artifactory/generic-local/mooc-team-two/
